blogs/urls.py
from django.urls import path
from blogs import views


app_name = 'blogs'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('homepage.urls', namespace='homepage')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('api/blogs/', include('blogs_api.urls', namespace='blogs-api')),

]

# serving static and media for development environment
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from accounts.models import User


# Create your models here.


class Post(models.Model):
    """
    This is Post model for defining the fields of Post model.
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='blogs/')
    title = models.CharField(max_length=200)
    content = models.TextField()
    status = models.BooleanField(default=False)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

blogs/views.py
from django.shortcuts import render

from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from blogs.models import Post


# Create your views here.


class IndexView(ListView):
    model = Post
    template_name = 'blogs/index.html'
    context_object_name = 'posts'


class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    # fields = "__all__"
    fields = ['title', 'image', 'content', 'status', 'category']
    template_name = 'blogs/post-create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blogs:index')


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'blogs/post-detail.html'
    context_object_name = 'post'


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    success_url = '/blogs/'
    fields = ['title', 'image', 'content', 'status', 'category']
    template_name = 'blogs/post-create.html'

    def get_success_url(self):
        return reverse_lazy('blogs:detail', kwargs={'pk': self.object.id})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post

    def get_success_url(self):
        return reverse_lazy('blogs:index')

blogs/templates/blogs/create-blog.html
{% extends 'base.html' %}
{% block title %}
    Create Blog
{% endblock %}

{% block content %}
    <h1>Create Blog</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

blogs/templates/blogs/index.html
{% extends 'base.html' %}
{% block title %}
    All Blogs
{% endblock %}

{% block content %}
    <h1>Blogs Page</h1>
    <hr>
    {% for post in posts %}
        <h4><a href="{% url 'blogs:detail' post.id %}">{{ post.title }}</a></h4>
        <p>{{ post.content }}</p>
        <hr>
    {% endfor %}
{% endblock %}

blogs/templates/blogs/post-create.html
{% extends 'base.html' %}
{% block title %}
    Create Blog
{% endblock %}

{% block content %}
    <h1>Create Blog</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

blogs/templates/blogs/post-detail.html
{% extends 'base.html' %}
{% block title %}
    Detail Blog
{% endblock %}

{% block content %}
    <a href="{% url 'blogs:update' post.id %}" class="btn btn-info"> Update </a>
    <a href="{% url 'blogs:delete' post.id %}" class="btn btn-danger"> Delete </a>
    <h1>{{ post.content }}</h1>
    <p>{{ post.author }}</p>

{% endblock %}

blogs/templates/blogs/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>