blogs/urls.py
from django.urls import path
from blogs import views


app_name = 'blogs'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('homepage.urls', namespace='homepage')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('api/blogs/', include('blogs_api.urls', namespace='blogs-api')),

]

# serving static and media for development environment
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from homepage import views


app_name = 'homepage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home')
]

templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}

        <p class="alert alert-{{ msg.tags }}"> {{ msg }} </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'homepage:home' %}"> Home </a>
        <a class="nav-item nav-link" href="{% url 'blogs:index' %}"> Blogs </a>
        <a class="nav-item nav-link" href="{% url 'blogs:create' %}"> Create </a>
    </div>
</nav>